### ISSUE TITLE
Sketch Installation not working anymore

### ISSUE THREAD

**Issue by virtualpatrick** [Installomator/Installomator#474] opened 2022-04-06 09:01 UTC
I tested this under macOS Monterey 12.3.1 on Intel and ARM Macs:

Script result: 2022-04-06 10:50:39 : REQ   :  : shifting arguments for Jamf
2022-04-06 10:50:39 : REQ   : sketch : ################## Start Installomator v. 9.1, date 2022-03-18
2022-04-06 10:50:39 : INFO  : sketch : ################## Version: 9.1
2022-04-06 10:50:39 : INFO  : sketch : ################## Date: 2022-03-18
2022-04-06 10:50:39 : INFO  : sketch : ################## sketch
2022-04-06 10:50:40 : INFO  : sketch : BLOCKING_PROCESS_ACTION=tell_user
2022-04-06 10:50:40 : INFO  : sketch : NOTIFY=success
2022-04-06 10:50:40 : INFO  : sketch : LOGGING=INFO
2022-04-06 10:50:40 : INFO  : sketch : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2022-04-06 10:50:40 : INFO  : sketch : Label type: zip
2022-04-06 10:50:40 : INFO  : sketch : archiveName: Sketch.zip
2022-04-06 10:50:40 : INFO  : sketch : no blocking processes defined, using Sketch as default
2022-04-06 10:50:40 : INFO  : sketch : name: Sketch, appName: Sketch.app
2022-04-06 10:50:40 : INFO  : sketch : App(s) found: 
2022-04-06 10:50:40 : WARN  : sketch : could not find Sketch.app
2022-04-06 10:50:40 : INFO  : sketch : appversion: 
2022-04-06 10:50:40 : INFO  : sketch : Latest version of Sketch is 85.1
2022-04-06 10:50:41 : REQ   : sketch : Downloading https://download.sketch.com/sketch-85.1-141321.ziptry again</a>.</p> to Sketch.zip
2022-04-06 10:50:41 : ERROR : sketch : error downloading https://download.sketch.com/sketch-85.1-141321.ziptry again</a>.</p>
ls: Sketch.zip: No such file or directory
2022-04-06 10:50:41 : ERROR : sketch : File list: 
2022-04-06 10:50:41 : ERROR : sketch : File type: Sketch.zip: cannot open `Sketch.zip' (No such file or directory)
2022-04-06 10:50:41 : INFO  : sketch : App not closed, so no reopen.
2022-04-06 10:50:41 : ERROR : sketch : ERROR: Error downloading https://download.sketch.com/sketch-85.1-141321.ziptry again</a>.</p> error:
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL

2022-04-06 10:50:41 : REQ   : sketch : ################## End Installomator, exit code 2

**Comment by andrewchenWP** [comment] 2022-04-08 14:12
it seems they renamed the zip name to include the version which is bonking the script. sketch-85.1-141321.zip

**Comment by 3BeersKen** [comment] 2022-04-08 18:14
It looks like the issue is in how sed is parsing out the downloadURL in line 4041.  Changing the line to the following fixes it.

`downloadURL=$(curl -sf https://www.sketch.com/downloads/mac/ | grep 'href="https://download.sketch.com' | sed -E 's/.*href=\"(.*)\".*/\1/g')`

**Comment by Theile** [comment] 2022-04-09 04:26
Fixed in #455.

**Closed** 2022-05-18 08:17 UTC
Labels: bug, application
