### ISSUE TITLE
Issue with clickshare

### ISSUE THREAD

**Issue by erppaul** [Installomator/Installomator#1182] opened 2023-08-23 22:32 UTC
Hi,
the download path and app version is incorrectly composed:
Download-URL: https://www.barco.com/ App-Version: Expected Team-ID: P6CDJZR997
It should be this one: https://www.barco.com/en/support/software/R3306192
Please can you fix this issue.

`An error occurred while running the policy "ClickShare [ latest version ]" on the computer "CECDEMBP-...". Actions from policy log: [STEP 1 of 5] Executing Policy ClickShare [ latest version ] [STEP 2 of 5] Running script Installomator 2... Script exit code: 22 Script result: 2023-08-24 00:26:31 : REQ : : shifting arguments for Jamf 2023-08-24 00:26:31 : REQ : clickshare : ################## Start Installomator v. 10.5beta, date 2023-08-23 2023-08-24 00:26:31 : INFO : clickshare : ################## Version: 10.5beta 2023-08-24 00:26:31 : INFO : clickshare : ################## Date: 2023-08-23 2023-08-24 00:26:31 : INFO : clickshare : ################## clickshare 2023-08-24 00:26:31 : DEBUG : clickshare : DEBUG mode 1 enabled. (eval):1: no such file or directory: https://www.barco.com/ Download-URL: https://www.barco.com/ App-Version: Expected Team-ID: P6CDJZR997 2023-08-24 00:26:31 : INFO : clickshare : setting variable from argument NOTIFY=silent 2023-08-24 00:26:31 : INFO : clickshare : setting variable from argument DEBUG=0 2023-08-24 00:26:31 : DEBUG : clickshare : name=ClickShare 2023-08-24 00:26:31 : DEBUG : clickshare : appName= 2023-08-24 00:26:31 : DEBUG : clickshare : type=appInDmgInZip 2023-08-24 00:26:31 : DEBUG : clickshare : archiveName= 2023-08-24 00:26:31 : DEBUG : clickshare : downloadURL=https://www.barco.com/ 2023-08-24 00:26:31 : DEBUG : clickshare : curlOptions= 2023-08-24 00:26:31 : DEBUG : clickshare : appNewVersion=0.0.0-b0 2023-08-24 00:26:31 : DEBUG : clickshare : appCustomVersion function: Not defined 2023-08-24 00:26:31 : DEBUG : clickshare : versionKey=CFBundleShortVersionString 2023-08-24 00:26:31 : DEBUG : clickshare : packageID= 2023-08-24 00:26:31 : DEBUG : clickshare : pkgName= 2023-08-24 00:26:31 : DEBUG : clickshare : choiceChangesXML= 2023-08-24 00:26:31 : DEBUG : clickshare : expectedTeamID=P6CDJZR997 2023-08-24 00:26:31 : DEBUG : clickshare : blockingProcesses= 2023-08-24 00:26:31 : DEBUG : clickshare : installerTool= 2023-08-24 00:26:31 : DEBUG : clickshare : CLIInstaller= 2023-08-24 00:26:31 : DEBUG : clickshare : CLIArguments= 2023-08-24 00:26:31 : DEBUG : clickshare : updateTool= 2023-08-24 00:26:31 : DEBUG : clickshare : updateToolArguments= 2023-08-24 00:26:31 : DEBUG : clickshare : updateToolRunAsCurrentUser= 2023-08-24 00:26:31 : INFO : clickshare : BLOCKING_PROCESS_ACTION=tell_user 2023-08-24 00:26:31 : INFO : clickshare : NOTIFY=silent 2023-08-24 00:26:31 : INFO : clickshare : LOGGING=DEBUG 2023-08-24 00:26:31 : INFO : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns 2023-08-24 00:26:31 : INFO : clickshare : Label type: appInDmgInZip 2023-08-24 00:26:31 : INFO : clickshare : archiveName: ClickShare.zip 2023-08-24 00:26:31 : INFO : clickshare : no blocking processes defined, using ClickShare as default 2023-08-24 00:26:31 : DEBUG : clickshare : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qisX6FMF 2023-08-24 00:26:31 : INFO : clickshare : name: ClickShare, appName: ClickShare.app 2023-08-24 00:26:31.713 mdfind[55034:444925] [UserQueryParser] Loading keywords and predicates for locale "en_US" 2023-08-24 00:26:31.714 mdfind[55034:444925] [UserQueryParser] Loading keywords and predicates for locale "en" 2023-08-24 00:26:31.773 mdfind[55034:444925] Couldn't determine the mapping between prefab keywords and predicates. 2023-08-24 00:26:31 : WARN : clickshare : No previous app found 2023-08-24 00:26:31 : WARN : clickshare : could not find ClickShare.app 2023-08-24 00:26:31 : INFO : clickshare : appversion: 2023-08-24 00:26:31 : INFO : clickshare : Latest version of ClickShare is 0.0.0-b0 2023-08-24 00:26:31 : REQ : clickshare : Downloading https://www.barco.com/ to ClickShare.zip 2023-08-24 00:26:31 : DEBUG : clickshare : No Dialog connection, just download 2023-08-24 00:26:33 : DEBUG : clickshare : File list: -rw-r--r-- 1 root wheel 430K Aug 24 00:26 ClickShare.zip 2023-08-24 00:26:33 : DEBUG : clickshare : File type: ClickShare.zip: HTML document text, Unicode text, UTF-8 text 2023-08-24 00:26:33 : DEBUG : clickshare : curl output was: * Trying 104.18.6.124:443... * Connected to www.barco.com (104.18.6.124) port 443 (#0) * ALPN: offers h2,http/1.1 * (304) (OUT), TLS handshake, Client hello (1): } [318 bytes data] * CAfile: /etc/ssl/cert.pem * CApath: none * (304) (IN), TLS handshake, Server hello (2): { [122 bytes data] * (304) (IN), TLS handshake, Unknown (8): { [19 bytes data] * (304) (IN), TLS handshake, Certificate (11): { [2319 bytes data] * (304) (IN), TLS handshake, CERT verify (15): { [79 bytes data] * (304) (IN), TLS handshake, Finished (20): { [36 bytes data] * (304) (OUT), TLS handshake, Finished (20): } [36 bytes data] * SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 * ALPN: server accepted h2 * Server certificate: * subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com * start date: Apr 18 00:00:00 2023 GMT * expire date: Apr 16 23:59:59 2024 GMT * subjectAltName: host "www.barco.com" matched cert's "www.barco.com" * issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3 * SSL certificate verify ok. * using HTTP/2 * h2 [:method: GET] * h2 [:scheme: https] * h2 [:authority: www.barco.com] * h2 [:path: /] * h2 [user-agent: curl/8.1.2] * h2 [accept: */*] * Using Stream ID: 1 (easy handle 0x143811600) > GET / HTTP/2 > Host: www.barco.com > User-Agent: curl/8.1.2 > Accept: */* > < HTTP/2 302 < date: Wed, 23 Aug 2023 22:26:33 GMT < content-type: text/html; charset=iso-8859-1 < location: https://www.barco.com/en < cache-control: no-store, no-cache, must-revalidate < expires: Thu, 01 Jan 1970 00:00:00 GMT < x-aem-client-country: DE < set-cookie: affinity="654018fc545ff3a5"; Path=/; HttpOnly < accept-ranges: bytes < strict-transport-security: max-age=31557600 < x-served-by: cache-ams21078-AMS < x-cache: MISS < x-timer: S1692829593.996744,VS0,VS0,VE4 < vary: x-aem-client-country,X-Forwarded-Host < cf-cache-status: DYNAMIC < server: cloudflare < cf-ray: 7fb6c71bdbf5aca4-TXL < * Ignoring the response-body { [594 bytes data] * Connection #0 to host www.barco.com left intact * Issue another request to this URL: 'https://www.barco.com/en' * Found bundle for host: 0x600001ec0ed0 [can multiplex] * Re-using existing connection #0 with host www.barco.com * h2 [:method: GET] * h2 [:scheme: https] * h2 [:authority: www.barco.com] * h2 [:path: /en] * h2 [user-agent: curl/8.1.2] * h2 [accept: */*] * Using Stream ID: 3 (easy handle 0x143811600) > GET /en HTTP/2 > Host: www.barco.com > User-Agent: curl/8.1.2 > Accept: */* > < HTTP/2 200 < date: Wed, 23 Aug 2023 22:26:33 GMT < content-type: text/html;charset=utf-8 < x-frame-options: SAMEORIGIN < x-aem-client-country: DE < last-modified: Wed, 23 Aug 2023 20:15:09 GMT < x-vhost: dxp < cache-control: max-age=900, stale-while-revalidate=60, stale-if-error=9000, public < set-cookie: affinity="1809e87975dcccc5"; Path=/; HttpOnly < x-content-type-options: nosniff < age: 0 < strict-transport-security: max-age=31557600 < x-served-by: cache-ams21078-AMS < x-cache: MISS < x-timer: S1692829593.043507,VS0,VS0,VE16 < vary: x-aem-client-country,Accept-Encoding,X-Forwarded-Host < cf-cache-status: DYNAMIC < server: cloudflare < cf-ray: 7fb6c71c6d0caca4-TXL < { [68941 bytes data] * Connection #0 to host www.barco.com left intact 2023-08-24 00:26:33 : REQ : clickshare : no more blocking processes, continue with update 2023-08-24 00:26:33 : REQ : clickshare : Installing ClickShare 2023-08-24 00:26:33 : INFO : clickshare : Unzipping ClickShare.zip tar: Error opening archive: Unrecognized archive format 2023-08-24 00:26:33 : DEBUG : clickshare : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qisX6FMF 2023-08-24 00:26:33 : DEBUG : clickshare : Debugging enabled, Deleting tmpDir output was: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qisX6FMF/ClickShare.zip 2023-08-24 00:26:33 : DEBUG : clickshare : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qisX6FMF 2023-08-24 00:26:33 : INFO : clickshare : App not closed, so no reopen. 2023-08-24 00:26:33 : ERROR : clickshare : ERROR: couldn't find dmg in zip ClickShare.zip 2023-08-24 00:26:33 : REQ : clickshare : ################## End Installomator, exit code 22 Error running script: return code was 22. [STEP 3 of 5] [STEP 4 of 5] Inventory will be updated when all queued actions in Self Service are complete. [STEP 5 of 5] The complete policy log is available in the JSS at: https://....jamfcloud.com/policies.html?id=271&o=l Computer Info: ID: 38 IP Address: 10.0.1.93 Serial Number: ...`

**Comment by erppaul** [comment] 2023-08-23 22:44
I have temporarily used the download link from this website: https://www.barco.com/en/support/software/R3306192
direct download:
https://barcoprdwebsitefs.azureedge.net/barcoprdfs/Data/secure/downloads/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_49_ApplicationSw.zip?AGNqlW7FJ7_ve9nCVJlvPcnpTDQ98EXfqpBhlY8oKWBOHkKeGNMeZPyn3fM9SSP6bh5p6KwXXr9-C6ZwvCpaxtPOigS7

**Comment by asri-tm** [comment] 2023-08-29 05:27
this is duplicate of #979 
Unfortunately the downloaded app versions are not matching the published version history

**Comment by kevinVodi** [comment] 2023-08-29 18:26
2023-08-29 11:24:06 : REQ   : clickshare : no more blocking processes, continue with update
2023-08-29 11:24:06 : REQ   : clickshare : Installing ClickShare
2023-08-29 11:24:06 : INFO  : clickshare : Unzipping ClickShare.zip
tar: Error opening archive: Unrecognized archive format
2023-08-29 11:24:06 : DEBUG : clickshare : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qgm4coat
2023-08-29 11:24:06 : DEBUG : clickshare : Debugging enabled, Deleting tmpDir output was:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qgm4coat/ClickShare.zip
2023-08-29 11:24:06 : DEBUG : clickshare : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.qgm4coat
2023-08-29 11:24:06 : INFO  : clickshare : App not closed, so no reopen.
2023-08-29 11:24:06 : ERROR : clickshare : ERROR: couldn't find dmg in zip ClickShare.zip
2023-08-29 11:24:06 : REQ   : clickshare : ################## End Installomator, exit code 22

**Closed** 2024-08-30 12:32 UTC
Labels: help wanted, application-issue
