### ISSUE TITLE
Homebrew fails with Exit Code 5 - Team IDs do not match!

### ISSUE THREAD

**Issue by JensTrendelkamp** [Installomator/Installomator#1792] opened 2024-08-20 10:10 UTC
> Script result: 2024-08-20 11:39:20 : REQ   :  : shifting arguments for Jamf
2024-08-20 11:39:20 : REQ   : homebrew : ################## Start Installomator v. 10.6beta, date 2024-04-23
2024-08-20 11:39:20 : INFO  : homebrew : ################## Version: 10.6beta
2024-08-20 11:39:20 : INFO  : homebrew : ################## Date: 2024-04-23
2024-08-20 11:39:20 : INFO  : homebrew : ################## homebrew
2024-08-20 11:39:20 : INFO  : homebrew : SwiftDialog is not installed, clear cmd file var
2024-08-20 11:39:21 : DEBUG : homebrew : name=Homebrew
2024-08-20 11:39:21 : DEBUG : homebrew : appName=
2024-08-20 11:39:21 : DEBUG : homebrew : type=pkg
2024-08-20 11:39:21 : DEBUG : homebrew : archiveName=Homebrew.pkg
2024-08-20 11:39:21 : DEBUG : homebrew : downloadURL=https://github.com/Homebrew/brew/releases/download/4.3.17/Homebrew-4.3.17.pkg
2024-08-20 11:39:21 : DEBUG : homebrew : curlOptions=
2024-08-20 11:39:21 : DEBUG : homebrew : appNewVersion=4.3.17
2024-08-20 11:39:21 : DEBUG : homebrew : appCustomVersion function: Not defined
2024-08-20 11:39:21 : DEBUG : homebrew : versionKey=CFBundleShortVersionString
2024-08-20 11:39:21 : DEBUG : homebrew : packageID=sh.brew.homebrew
2024-08-20 11:39:21 : DEBUG : homebrew : pkgName=
2024-08-20 11:39:21 : DEBUG : homebrew : choiceChangesXML=
2024-08-20 11:39:21 : DEBUG : homebrew : expectedTeamID=6248TWFRH6
2024-08-20 11:39:21 : DEBUG : homebrew : blockingProcesses=
2024-08-20 11:39:21 : DEBUG : homebrew : installerTool=
2024-08-20 11:39:21 : DEBUG : homebrew : CLIInstaller=
2024-08-20 11:39:21 : DEBUG : homebrew : CLIArguments=
2024-08-20 11:39:21 : DEBUG : homebrew : updateTool=
2024-08-20 11:39:21 : DEBUG : homebrew : updateToolArguments=
2024-08-20 11:39:21 : DEBUG : homebrew : updateToolRunAsCurrentUser=
2024-08-20 11:39:21 : INFO  : homebrew : BLOCKING_PROCESS_ACTION=tell_user
2024-08-20 11:39:21 : INFO  : homebrew : NOTIFY=all
2024-08-20 11:39:21 : INFO  : homebrew : LOGGING=DEBUG
2024-08-20 11:39:21 : INFO  : homebrew : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-08-20 11:39:21 : INFO  : homebrew : Label type: pkg
2024-08-20 11:39:21 : INFO  : homebrew : archiveName: Homebrew.pkg
2024-08-20 11:39:21 : INFO  : homebrew : no blocking processes defined, using Homebrew as default
2024-08-20 11:39:21 : DEBUG : homebrew : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.rcZW4U1EJe
2024-08-20 11:39:21 : INFO  : homebrew : No version found using packageID sh.brew.homebrew
2024-08-20 11:39:21 : INFO  : homebrew : name: Homebrew, appName: Homebrew.app
2024-08-20 11:39:21.819 mdfind[11186:109991] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2024-08-20 11:39:21.819 mdfind[11186:109991] [UserQueryParser] Loading keywords and predicates for locale "en"
2024-08-20 11:39:21.856 mdfind[11186:109991] Couldn't determine the mapping between prefab keywords and predicates.
2024-08-20 11:39:21 : WARN  : homebrew : No previous app found
2024-08-20 11:39:21 : WARN  : homebrew : could not find Homebrew.app
2024-08-20 11:39:21 : INFO  : homebrew : appversion: 
2024-08-20 11:39:21 : INFO  : homebrew : Label is not of type “updateronly”, and it’s set to use force to install or ignoring app store apps, so not using updateTool.
2024-08-20 11:39:21 : INFO  : homebrew : Latest version of Homebrew is 4.3.17
2024-08-20 11:39:21 : REQ   : homebrew : Downloading https://github.com/Homebrew/brew/releases/download/4.3.17/Homebrew-4.3.17.pkg to Homebrew.pkg
2024-08-20 11:39:21 : INFO  : homebrew : notifying
displaynotification:7: no such file or directory: /usr/local/bin/dialog
2024-08-20 11:39:21 : DEBUG : homebrew : No Dialog connection, just download
2024-08-20 11:40:01 : DEBUG : homebrew : File list: -rw-r--r--  1 root  wheel    99M Aug 20 11:40 Homebrew.pkg
2024-08-20 11:40:01 : DEBUG : homebrew : File type: Homebrew.pkg: xar archive compressed TOC: 4967, SHA-1 checksum
2024-08-20 11:40:02 : REQ   : homebrew : no more blocking processes, continue with update
2024-08-20 11:40:02 : REQ   : homebrew : Installing Homebrew
2024-08-20 11:40:02 : INFO  : homebrew : notifying
displaynotification:7: no such file or directory: /usr/local/bin/dialog
2024-08-20 11:40:02 : INFO  : homebrew : Verifying: Homebrew.pkg
2024-08-20 11:40:02 : DEBUG : homebrew : File list: -rw-r--r--  1 root  wheel    99M Aug 20 11:40 Homebrew.pkg
2024-08-20 11:40:02 : DEBUG : homebrew : File type: Homebrew.pkg: xar archive compressed TOC: 4967, SHA-1 checksum
2024-08-20 11:40:02 : DEBUG : homebrew : spctlOut is Homebrew.pkg: accepted
2024-08-20 11:40:02 : DEBUG : homebrew : source=Notarized Developer ID
2024-08-20 11:40:02 : DEBUG : homebrew : origin=Developer ID Installer: Patrick Linnane (927JGANW46)
2024-08-20 11:40:02 : INFO  : homebrew : Team ID: 927JGANW46 (expected: 6248TWFRH6 )
2024-08-20 11:40:02 : DEBUG : homebrew : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.rcZW4U1EJe
2024-08-20 11:40:02 : DEBUG : homebrew : Debugging enabled, Deleting tmpDir output was:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.rcZW4U1EJe/Homebrew.pkg
2024-08-20 11:40:02 : DEBUG : homebrew : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.rcZW4U1EJe
2024-08-20 11:40:02 : INFO  : homebrew : Installomator did not close any apps, so no need to reopen any apps.
2024-08-20 11:40:02 : ERROR : homebrew : ERROR: Team IDs do not match!
2024-08-20 11:40:02 : REQ   : homebrew : ################## End Installomator, exit code 5

**Comment by acodega** [comment] 2024-09-02 02:35
Duplicate of #1726 which has a PR which will be merged soon.

**Closed by acodega** 2024-09-02 02:35 UTC
