### ISSUE TITLE
Error installing GIMP

### ISSUE THREAD

**Issue by JMEngineeringMacOS** [Installomator/Installomator#1755] opened 2024-07-17 05:06 UTC
2024-07-17 13:27:03 : INFO  : gimp : Latest version of GIMP is https://
2024-07-17 13:27:03 : REQ   : gimp : Downloading https:// to GIMP.dmg
2024-07-17 13:27:03 : ERROR : gimp : error downloading https://
ls: GIMP.dmg: No such file or directory
2024-07-17 13:27:03 : ERROR : gimp : File list: 
2024-07-17 13:27:03 : ERROR : gimp : File type: GIMP.dmg: cannot open `GIMP.dmg' (No such file or directory)
2024-07-17 13:27:03 : INFO  : gimp : Installomator did not close any apps, so no need to reopen any apps.
2024-07-17 13:27:03 : ERROR : gimp : ERROR: Error downloading https:// error:
* URL rejected: No host part in the URL
* Closing connection
curl: (3) URL rejected: No host part in the URL

**Comment by hwlans** [comment] 2024-07-17 15:01
#1680

**Comment by Isokoloff** [comment] 2024-09-06 16:23
See new comment in issue cited by @hwlans; merge has not yet occurred, issue remains present in Installomator 10.6 with current GIMP DMG revision 1 versions

**Comment by acodega** [comment] 2024-09-06 17:39
I believe this Issue is a duplicate of #1676. It will be fixed once #1680 gets merged.

**Closed by acodega** 2024-09-06 17:39 UTC
