### ISSUE TITLE
Figma pulling previous app version

### ISSUE THREAD

**Issue by Turb0n00by** [Installomator/Installomator#397] opened 2022-01-31 21:13 UTC
Hi,

I'm testing Installomater (amazing so far!) and noticed that Figma is pulling a previous release down when using an intel based MacBook. The built in script pulls 107.x and current revision is 108.x.  Is there a setting or troubleshooting steps I should try?

Thank you

**Comment by Theile** [comment] 2022-02-01 12:49
I don't see version 108 anywhere, and not from release:
```
curl -fsL https://desktop.figma.com/mac/RELEASE.json
{ "url": "https://desktop.figma.com/mac/Figma-107.1.0.zip", "version": "107.1.0", "stage": 100 }
```

So where do you get that version from?

**Comment by acodega** [comment] 2022-02-02 15:59
I'm not seeing version 108 either. Are there release notes or etc available?

**Comment by Turb0n00by** [comment] 2022-02-03 13:04
Hi and thank you for you replies..

I did some more digging on my end, and found that it is the M1 Pro device has found a way to pull down and install v108.1.x using installomator when referencing v108.1.0 and within our Jamf Pro console under Patch management as current release(working as designed from a workflow perspective). The installed app shows v.108.1, and attempting to manually download the app from the curl command in the .sh script does pull 107.x as you guys are seeing.  I took some screen shots of the console and the app version installed on the M1 Pro (I'm not sure if I am allowed to post a picture or link to a 3rd party site without violation of policy or I would have them on this reply).  

Looking at https://macupdater.net/app_updates/appinfo/com.figma.DesktopBeta/index.html I can see that 108.x was a beta release on 1-4-22, and according to the Jamf console was released to production (based off nothing more than their software titles for patching) on 1-18-22.  Normally I would write this off as a Jamf product issue, but somehow I was able to get this release using nothing more than installomater. I dont use Figma at all and I know I am not enrolled in any sort of beta program of theirs. 

I am going to do a full device wipe on the M1 and test it again in the next day or so and will test on another Intel machine (though that seems to be pulling 107.x too). I will keep you posted!

**Comment by Theile** [comment] 2022-02-08 09:15
It could be possible that it was listed in the RELEASE.json for some time and then pulled again. We have no way of knowing that. We only know that each developer seems to post releases in different ways. I will close this, as I think the problem is out of our hands anyway.

**Closed by Theile** 2022-02-08 09:15 UTC
Labels: application
