### ISSUE TITLE
python label broken

### ISSUE THREAD

**Issue by rtbrown76** [Installomator/Installomator#1747] opened 2024-07-10 16:24 UTC
2024-07-10 11:30:51 : ERROR : python : ERROR: Error verifying Python.pkg error: Python.pkg: rejected source=no usable signature 2024-07-10 11:30:51 : REQ : python : ################## End Installomator, exit code 4

**Comment by acodega** [comment] 2024-09-17 13:33
Duplicate of #1692 . I happen to be working on a fix today.. should have a PR soon.

**Closed by acodega** 2024-09-17 13:33 UTC
