### ISSUE TITLE
4kdownloader now produces URL error

### ISSUE THREAD

**Issue by starlord1980** [Installomator/Installomator#1144] opened 2023-07-19 10:49 UTC
Looks like 4kdownloader has added a + to the name of the app, so the URL is now broken.

```
Script result: 2023-07-17 13:00:38 : REQ   :  : shifting arguments for Jamf
2023-07-17 13:00:38 : REQ   : 4kvideodownloader : ################## Start Installomator v. 10.4, date 2023-06-02
2023-07-17 13:00:38 : INFO  : 4kvideodownloader : ################## Version: 10.4
2023-07-17 13:00:38 : INFO  : 4kvideodownloader : ################## Date: 2023-06-02
2023-07-17 13:00:38 : INFO  : 4kvideodownloader : ################## 4kvideodownloader
2023-07-17 13:00:38 : DEBUG : 4kvideodownloader : DEBUG mode 1 enabled.
2023-07-17 13:00:38 : INFO  : 4kvideodownloader : SwiftDialog is not installed, clear cmd file var
2023-07-17 13:00:40 : INFO  : 4kvideodownloader : setting variable from argument NOTIFY=silent
2023-07-17 13:00:40 : INFO  : 4kvideodownloader : setting variable from argument DEBUG=0
2023-07-17 13:00:40 : ERROR : 4kvideodownloader : need to provide 'downloadURL'
```

**Comment by acodega** [comment] 2024-08-31 20:39
Duplicate of #1164

**Closed by acodega** 2024-08-31 20:39 UTC
Labels: help wanted, application-issue
