### ISSUE TITLE
Adobe Creative Cloud URLs are swapped

### ISSUE THREAD

**Issue by kylejericson** [Installomator/Installomator#686] opened 2022-09-12 16:21 UTC
This is the current code for adobecreativeclouddesktop: 
Note the arm64 is pulling the Intel installer and the Intel is pulling the Arm installer

if [[ $(arch) == "arm64" ]]; then
        downloadURL=$(curl -fs "$adobeurl" | xmllint -html -xpath "string(//a[contains(@href,'osx10')][contains(text(),'Download')]/@href)" - 2> /dev/null)
    elif [[ $(arch) == "i386" ]]; then
        downloadURL=$(curl -fs "$adobeurl" | xmllint -html -xpath "string(//a[contains(@href,'macarm64')][contains(text(),'Download')]/@href)" - 2> /dev/null)
    fi

#Fixed Code:

if [[ $(arch) == "arm64" ]]; then
            downloadURL=$(curl -fs "$adobeurl" | xmllint -html -xpath "string(//a[contains(@href,'macarm64')][contains(text(),'Download')]/@href)" - 2> /dev/null)

    elif [[ $(arch) == "i386" ]]; then
                downloadURL=$(curl -fs "$adobeurl" | xmllint -html -xpath "string(//a[contains(@href,'osx10')][contains(text(),'Download')]/@href)" - 2> /dev/null)
fi

**Comment by kylejericson** [comment] 2022-09-12 16:28
Sorry github hates me and won't let code block this

**Comment by acodega** [comment] 2022-09-12 16:40
I'm going to close this since it's a duplicate of https://github.com/Installomator/Installomator/issues/674

**Closed by acodega** 2022-09-12 16:40 UTC
Labels: application, bug-fix
