### ISSUE TITLE
Broken app label: [1Password8]

### ISSUE THREAD

**Issue by cascaderek** [Installomator/Installomator#2056] opened 2024-12-03 19:31 UTC
**What's wrong with the app label?**
The 1Password app requires end users to enter the admin password to complete updates, rather than processing them through a popup like other applications.

**Installomator version**
Installomator v. 10.6, 2 December 2024.

**Additional context**
I was using Installomator 10.3 when a banner appeared stating, "Quit 1Password to continue updating?" with the options "Not Now" or "Quit and Update." However, the banner kept reappearing regardless of the option selected, and the update did not proceed. We updated the script in our MDM (Jamf) to Installomator 10.6.

**Installomator log**
[Installomator Log.pdf](https://github.com/user-attachments/files/17997952/Installomator.Log.pdf)

**Comment by rderewianko** [comment] 2024-12-05 12:30
This is a dupe of: #2029

For those of us who don't want to download a PDF
```Executing Policy App Update - 1Password‬
‭ Running script Installomator 10.3...‬
‭ Script exit code: 11‬
‭ Script result: 2024-11-05 13:23:30 : REQ : : shifting arguments for Jamf‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : setting variable from argument DEBUG=0‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : setting variable from argument‬
‭ BLOCKING_PROCESS_ACTION=prompt_user_then_kill‬
‭ 2024-11-05 13:23:30 : REQ : 1password8 : ################## Start Installomator v. 10.3, date 2023-02-10‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : ################## Version: 10.3‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : ################## Date: 2023-02-10‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : ################## 1password8‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : SwiftDialog is not installed, clear cmd file var‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : BLOCKING_PROCESS_ACTION=prompt_user_then_kill‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : NOTIFY=success‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : LOGGING=INFO‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : LOGO=/System/Applications/App‬
‭ Store.app/Contents/Resources/AppIcon.icns‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : Label type: pkg‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : archiveName: 1Password.pkg‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : found packageID com.1password.1password installed, version 8.10.46‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : appversion: 8.10.46‬
‭ 2024-11-05 13:23:30 : INFO : 1password8 : Latest version not specified.‬
‭ 2024-11-05 13:23:30 : REQ : 1password8 : Downloading https://downloads.1password.com/mac/1Password.pkg to‬
‭ 1Password.pkg‬
‭ 2024-11-05 13:23:47 : INFO : 1password8 : found blocking process 1Password‬
‭ 2024-11-05 13:23:50 : INFO : 1password8 : telling app 1Password to quit‬
‭ 2024-11-05 13:23:51 : INFO : 1password8 : waiting 30 seconds for processes to quit‬
‭ 2024-11-05 13:24:21 : INFO : 1password8 : found blocking process 1Password‬
‭ 2024-11-05 13:24:25 : INFO : 1password8 : telling app 1Password to quit‬
‭ 2024-11-05 13:24:25 : INFO : 1password8 : waiting 30 seconds for processes to quit‬
‭ 2024-11-05 13:24:56 : INFO : 1password8 : found blocking process 1Password‬
‭ 2024-11-05 13:25:04 : INFO : 1password8 : Changing BLOCKING_PROCESS_ACTION to kill‬
‭ 2024-11-05 13:25:05 : INFO : 1password8 : found blocking process 1Password‬
‭ 2024-11-05 13:25:05 : INFO : 1password8 : killing process 1Password‬
‭ 2024-11-05 13:25:10 : INFO : 1password8 : Telling app 1Password.app to open‬
‭ 2024-11-05 13:25:10 : INFO : 1password8 : Reopened 1Password.app as [username ommitted]‬
‭ 2024-11-05 13:25:10 : ERROR : 1password8 : ERROR: could not quit all processes, aborting...‬
‭ 2024-11-05 13:25:10 : REQ : 1password8 : ################## End Installomator, exit code 11‬
‭ Error running script: return code was 11.‬
‭ Running Recon...‬
‭ Retrieving inventory preferences from https://[ommitted].jamfcloud.com/...‬
‭ Locating accounts...‬
‭ Locating package receipts...‬
‭ Searching path: /System/Applications‬
‭ Locating printers...‬
‭ Gathering application usage information from the JamfDaemon...‬
‭ Searching path: /Applications‬
‭ Locating hardware information (macOS 14.4.1)...
```

**Comment by acodega** [comment] 2024-12-18 12:26
Closing duplicate.

**Closed by acodega** 2024-12-18 12:26 UTC
Labels: application-issue
